apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-run
spec:
  pipelineRef:
    name: sample
  params:
  - name: image
    value: ttl.sh/testing/test:2
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: source-pvc
