apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-run
spec:
  pipelineRef:
    name: sample
  params:
  - name: image
    value: ttl.sh/ttttesting/test:kaniko
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: source-pvc
  - name: ssh-creds
    secret:
      secretName: deploy-key
