# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: source-pvc
# spec:
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 2Gi
#   # storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
#   volumeName: source-pvc
#   accessModes:
#   - ReadWriteOnce
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
